name: rick_and_morty_lesson
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.6.2
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  dio: ^5.7.0
  logger: ^2.5.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  retrofit_generator: ^9.1.5
  build_runner: ^2.4.14
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.8.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/

